### ISSUE TITLE
c5e24

### ISSUE THREAD

**Issue by odanoburu** [arademaker/CS-FP#5]
o primeiro item desse exercício me levou a [esta discussão](https://math.stackexchange.com/questions/449418/why-does-the-semantics-of-first-order-logic-require-the-domain-to-be-non-empty).

outros links: [1](https://en.wikipedia.org/wiki/Empty_domain) [2](https://en.wikipedia.org/wiki/Free_logic).

**Comment by arademaker** [comment]
Bem, o link https://plato.stanford.edu/entries/logic-free/#3 é o mais completo sobre o assunto. Mas não acho que vale a pena entrarmos nesta discussão.  Existem _várias_ lógicas além da lógica clássica.

E sim, é verdade que o primeiro item é apenas válido se consideramos domínios não vazios.

**Comment by odanoburu** [comment]
justo, é só uma curiosidade mesmo!
