### ISSUE TITLE
definição de Ã

### ISSUE THREAD

**Issue by odanoburu** [arademaker/CS-FP#9]
no capítulo 5 do livro (seção 7, p. 108), os autores definem:

    The rules of the inference engine are the following. Let Ã be given by: 
    if A is of the form ~C, then Ã = C, otherwise Ã=~A. 

em que ~A é o complemento de A. pelo que entendi, Ã é equivalente ao complemento de A, de modo que não entendi o propósito dessa definição. entendi errado?

**Comment by arademaker** [comment]
Acho que concordamos que a forma mais simples de entender é que opp abaixo é o `~` e `OppClass` é o `\overbar{a}` (LaTeX) em

```
data Class = Class String | OppClass String 
             deriving (Eq,Ord)

instance Show Class where 
  show (Class xs)    = xs
  show (OppClass xs) = "non-" ++ xs 

opp :: Class -> Class
opp (Class name)    = OppClass name
opp (OppClass name) = Class name
```
